### ISSUE TITLE
[1.0.0.25] ArrayIndexOutofBoundsException on startup

### ISSUE THREAD

**Issue by Rikshy** [wendall911/TinkerSurvival#1]
Hey there,

guess i'm the first :D

I get the named Exception here [here](https://github.com/wendall911/TinkerSurvival/blob/945fdf5845049983db1235410a993c91f8ea2b2f/src/main/java/tinkersurvival/recipe/TinkerSurvivalRecipes.java#L153)

First i thought for some reason my already disabled plank recipes would cause it (CraftTweaker), but that should happen way later, right?

Since you are already checking the array size of the Ingredients, it should be `getMatchingStacks()[0]` then?

i am super excited to test your mod, so hopefully we can sort this out :)

forge version: 2702
mod version: 1.0.0.25
fullcrash log: [pastebin](https://pastebin.com/srtJzXL1)

**Comment by wendall911** [comment]
Hey, thanks for the report! CraftTweaker changed the way it works to run earlier in the process. I depend on the plank recipes for 2 reasons:
1. I use the default recipes to create ones that work for the saw.
2. I replace them with an empty dummy recipe

I can run a check to see if the recipe has valid output, but basically the saw would be useless with the recipes already disabled.

Thoughts?

**Comment by Rikshy** [comment]
Maybe add a config option PlanksNeedSawToCraft, just to make it more visible to the user what might go on.

imho it's not too bad to make the saw useless, some modpack makers might want to use another way for early game wood.


So i disabled my CT script for the wood and it still crashes, there must be another mod - i am not aware of atm - that messes around with log recipes, which is wierd. But that should not be of you concern :)

**Comment by Rikshy** [comment]
Okay, so after some testing i found that it crashes with Aether II installed.
Maybe because of recipies like this:
![image](https://user-images.githubusercontent.com/6615662/40774343-9f5eb5c4-64c5-11e8-941f-092029a9f0ac.png)

EDIT: I also disabled this with CT and it still broke :(


PS of topic:
While looking through your code, wouldn't `recipe.getIngredients().size() > 0 && recipe.getIngredients().size() < 2` the same as `recipe.getIngredients().size() == 1`? :D

**Comment by wendall911** [comment]
Ok, I will do some more testing and have a fix out today. Maybe they are putting in empty item stacks as a dummy recipe similar to what I'm doing to disable some log recipes. I'll test and figure it out. Easy enough to add a conditional so it won't crash.

Great catch on the conditional! I am working with my son on this mod. He's just learning programming. I used that as a way to show useless, but harmless checks while we were working on that area. I didn't change it back for some reason, lol.

**Comment by Rikshy** [comment]
Uh, thats an awesome way showing programming! Hope you guys having fun! :)
The code is very much readable and understandable! Keep up the good work :D

And thanks for the quick reply and fix!

**Comment by wendall911** [comment]
Ok, they had a bad recipe. I need to check the array length before querying anyhow, that was just bad code. Thank you so much for the bug report! Much appreciated :+1:

**Comment by wendall911** [comment]
I'll roll a new release shortly.

**Comment by Rikshy** [comment]
No sweat! :) [although its pretty hot here and i'm almost melting]

I've been browsing through that piece of code a little.
Saw you iterating through all items to get planks:

`for (Item i : ForgeRegistries.ITEMS) {`

would it be an improvement to use the OreDict for that instead?

`net.minecraftforge.oredict.OreDictionary.getOres("plankWood");`
`net.minecraftforge.oredict.OreDictionary.getOres("stickWood");`

I am by no means an expert on minecraft modding, just a developer myself and curious :)

**Comment by wendall911** [comment]
That is how I did it before. The issue is that a lot of mods don't use the
oredict correctly. In fact, I think Natura is one of them. That is
certainly the correct way to do this.

What would make the code cleaner is if I had a helper function that made
sure items are in the oredict. Then fix this code to query the oredict.

Also, keep the comments coming. I haven't coded anything in Java in over 10
years, so any suggestions are super helpful.

**Comment by Rikshy** [comment]
tbh, i haven't coded in java at all -> C# dev (ok, maybe a little back in school :p)

So you want to ensure your mod can't be "exploited" by other mods, hmm.

Imho it shouldn't be your job to check it tho, rather talk to the dev who does it wrong or let the pack dev handle it (pack devs using your mod would do that anyway).
With `itemName.contains("planks")` you could also get items registered as "planksaw" or from the mod "moreplanks" (if those exist), right?

Thanks for being so open minded btw, :)


btw: do you know which of their recipes was the bad one?

**Comment by wendall911** [comment]
Ok, I just coded a test to refresh my memory. It turns out I can do it this way, (minus a couple small exceptions that I can account for). I also need to wait to register my recipes until postInit so it can pick up all the oreDict changes. But, yeah, doing string searches by name is pretty bad really.

Yeah, it isn't so much about being exploited. It is that the mod is built around the concept that punching trees and crafting without a saw is silly.

**Comment by wendall911** [comment]
Ok, much better now. Properly using oredict. I think this should map fairly well for most cases. The log/plank/stick recipes in Aether II aren't replaced, since those aren't properly registered in the oredict. Maybe they'll do that at some point, it is in alpha.

Anyhow, thanks for the feedback, greatly appreciated!
