### ISSUE TITLE
tinkersurvuval block ic2 wrench?

### ISSUE THREAD

**Issue by ryanwang0521** [wendall911/TinkerSurvival#35]
Even i set the config,ic2 wrench cant work with this mod in survival mode
how to fix it?
   
general {

    tools {
        # List of mods that tools will always work for. All other mod tools will become wet noodles.
        S:MOD_TOOL_WHITELIST <
            opencomputers
            tconstruct
            tinkersurvival
            ic2
         >

        # List of individual tools that will always work. Format tooltype-modid:item
        S:TOOLS_WHITELIST <
            shears-minecraft:shears
            hammer-immersiveengineering:tool
            wirecutter-immersiveengineering:tool
            sword-immersiveengineering:revolver
            sword-immersiveengineering:railgun
            pickaxe-immersiveengineering:drill
            wrench-ic2:wrench
            wrench-ic2:electric-wrench
         >
    }

**Comment by wendall911** [comment]
Let me work on this and see what the issue is. Your config looks correct.

**Comment by wendall911** [comment]
Ok, I added some code to make this work. I also added the ic2 wrench to the default config for reference. The issue here is that ic2 makes the wrench a pickaxe. It sets the harvest level for the tool at -1, but all machine blocks at harvest level 1. So whitelisting could never work because the harvest level was too low. What I've done is that for wrenches, and only wrenches, if the block being interacted with is the same as the wrench, then we just ignore harvest levels and let it work how the mod intends. It is a bit of a hack, but probably easier than having ic2 fix the issue.

Thanks for the report!
