### ISSUE TITLE
The ic2 wrench always do not work

### ISSUE THREAD

**Issue by linxcy** [wendall911/TinkerSurvival#57]
When l join a world, the wrench and the electric wrench work for the first time.
But when i try to remove the machine second time ,it does not work.
The minecraft vision is 1.12.2

**Comment by wendall911** [comment]
Can you share your config here?

**Comment by linxcy** [comment]
![image](https://user-images.githubusercontent.com/67699852/161874685-f0aa93a8-0af3-422e-814a-0d1e4e6b7471.png)


> Can you share your config here?

**Comment by wendall911** [comment]
Ok, I'll take a look at this. Just right away, the wild card will not work.
Let me check and see what the setting needs to be. I'll reply here sometime
tomorrow.

**Comment by wendall911** [comment]
Yeah, it looks like the latest ic2 broke this again. The code is just bad for that mod. It is closed source, so I have no way of even looking into what the issue is. They do some really, really weird things with their tools. I fixed this for an earlier version in this issue: https://github.com/wendall911/TinkerSurvival/issues/35 But really, the only fix is to just whitelist the ic2 mod entirely. I'm not doing any more updates for 1.12, so this isn't going to get fixed unless ic2 becomes open source and get proper fixes.

**Comment by linxcy** [comment]
It is easy to remove the tools or armors.
But the problem is that you cannot remove the machine without wrench.
I try to add ic2 into the mod white list, while it do not work.  
Or is it possible for you to add an option to disable the features that disable vanilla tools?

**Comment by linxcy** [comment]
> Yeah, it looks like the latest ic2 broke this again. The code is just bad for that mod. It is closed source, so I have no way of even looking into what the issue is. They do some really, really weird things with their tools. I fixed this for an earlier version in this issue: #35 But really, the only fix is to just whitelist the ic2 mod entirely. I'm not doing any more updates for 1.12, so this isn't going to get fixed unless ic2 becomes open source and get proper fixes.

It is easy to remove the tools or armors.
But the problem is that you cannot remove the machine without wrench.
I try to add ic2 into the mod white list, while it do not work.
Or is it possible for you to add an option to disable the features that disable vanilla tools?

**Comment by wendall911** [comment]
I just tested this locally a while ago and it works fine. Here is the config:

    tools {
        # List of mods that tools will always work for. All other mod tools will become wet noodles.
        S:MOD_TOOL_WHITELIST <
            tconstruct
            tinkersurvival
            ic2
         >

        # List of individual tools that will always work. Format tooltype-modid:item
        S:TOOLS_WHITELIST <
            wrench-ic2:wrench
            wrench-ic2:wrench_new
            wrench-ic2:electric_wrench
         >
    }

**Comment by linxcy** [comment]
![image](https://user-images.githubusercontent.com/67699852/162034546-64647a05-6680-429f-aff4-71d1507b69f5.png)
![image](https://user-images.githubusercontent.com/67699852/162034588-263ee7ec-661d-42d7-bcb8-ae2e9f457a0d.png)
Well, l don't know why i can not remove.

**Comment by wendall911** [comment]
Ok, you are correct. This is a bug. I didn't plan on having any more updates. Let me see if I can even build this and test. I'll reopen for now. The issue is that the NBT data when the item is damaged somehow messes with the detection. Actually just whitelisting should help.

As an aside. I absolutely hate supporting closed-source mods. I'll do this, but really am probably just going to automatically close issues in the future related to closed mods.

**Comment by linxcy** [comment]
i see,the closed-source mods are really hard to be compatible with.
Beside this ,thank you for fixing this bug. Really helped.

**Comment by wendall911** [comment]
I submitted a bug fix. You should just need the tools in the whitelist and it will work. 

Give a few minutes for the jar to get approved.

[TinkerSurvival-1.12.2-1.2.2.2.jar](https://www.curseforge.com/minecraft/mc-mods/tinkersurvival/files/3737445)

This is a weird issue where the harvest level of ic2 wrenches is now set to -1 and machines have a harvest level of 0. They did fix the bug where the wrench wasn't even registered correctly.

**Comment by linxcy** [comment]
well，it's me again.
the same problem appear on the ic2 addons mod again.
this is the main page of the mod on curse forge.
https://www.curseforge.com/minecraft/mc-mods/industrial-upgrade
and i'm using this vision IndustrialUpgrade-1.4.0.2.
