### ISSUE TITLE
Cannot whitelist individual tools that are not base game related

### ISSUE THREAD

**Issue by Dragnier** [wendall911/TinkerSurvival#6]
I want to whitelist Base Metals stone crackhammer, but no matter how I try to set it up in the individual tool whitelist it doesn't work. I also don't want to whitelist the entire mod's set of tools as I only want people to use them in Tinkers tools.

I've tried:

pick-basemetals:stone_crackhammer
pickaxe-basemetals:stone_crackhammer
crackhammer-basemetals:stone_crackhammer

None work. I do plan to change the recipe to make the crackhammer in question a bit harder to get in my pack so it doesn't let people bypass too much in the way of tinkers tools though. But I can't even mess with that until they work.

**Comment by wendall911** [comment]
Great suggestion. I've been considering how to do this. I'll think about the formatting. I think it would be good to allow others to register crude tools for certain items as well. We ban the crackhammer, since it bypasses a lot of gameplay, but it sounds like you have a good approach as well. I'll work on a solution for this. I may release it as a beta and allow you to mess around with it and see if it works for your situation.

**Comment by Dragnier** [comment]
Yeah, I only want the stone one whitelisted (personally) and I'm going to change the recipe to use the Tinkers stone hammer head and two tough tool rods instead of just smooth stone and two sticks.
