### ISSUE TITLE
1.18 zh_cn.json

### ISSUE THREAD

**Issue by deshark42** [wendall911/TinkerSurvival#90]
This is not a bug.

[zh_cn.json.zip](https://github.com/wendall911/TinkerSurvival/files/10480781/zh_cn.json.zip)

This is a 1.18 zh_cn.json that was modified from the #19 . I think adding it in the next update will avoid bad Chinese translations.
: )

**Comment by wendall911** [comment]
Can you explain what is changed in this? I will only accept PRs for translations now with a second native speaker confirming the translation.

**Comment by MicroNeutron** [comment]
For example when you try to sleep at night and faild. In English it said "Not sleepy, but spawn set!". But in original Chinese translation it said "睡你麻痹起来嗨" which means "sleep with your mother's ****, wake up for high up". and when you make an useless weapon. In English it said "This weapon hits like a wet noodle!". And in original Chinese taranslation it said "这破玩意跟你的**一样软" which means "This s**k is as soft as your d**k!". 
![image](https://github.com/wendall911/TinkerSurvival/assets/90130404/5b3dd893-7240-4670-9076-dbd313f5077b)
![image](https://github.com/wendall911/TinkerSurvival/assets/90130404/17982889-631d-4d25-982e-05a28f72c2d5)
This translation made very bad effect in Chinese community. Most Chinese players didn't know the problem was because of the disastrous translation. 
Whatever who is submitting translation like this. It is a rude and immoral. 
![image](https://github.com/wendall911/TinkerSurvival/assets/90130404/721acec1-c53d-4366-bfb0-54b50a29c011)
![image](https://github.com/wendall911/TinkerSurvival/assets/90130404/497993b6-79ce-4b0f-acb8-8675533e45e0)
For this problem, Chinese localize team CFPA made a correction on it. In the correction all translations looks polite and civillized. In the correction it also translated all of menus in the config file that the origin translation didn't translate any. 
We all think the new translation is much better than original one and hope this will become this translation wil be the official one to replace the original one. I believe it can take better environment and effect for Chinese communities and players.

**Comment by wendall911** [comment]
Thank you. This is greatly appreciated. I have a new process for accepting translations, so this shouldn't happen in the future.

I will update this tomorrow and let you know.

**Comment by wendall911** [comment]
I still don't think this is a very good translation. I updated it, and there are still some missing things. I will ask for some help from some users for our other mods and see if they can help with something better.

I agree that the offensive stuff should be removed. The intent is to be clever. These translations are actually really boring and miss the meaning entirely. I'll live with it for now, but this doesn't really fit the intention nor meaning of the original text for many of the items.

I greatly appreciate pointing this out to me.

**Comment by wendall911** [comment]
Release is up on CurseForge and Modrinth
